spring.application.name=LMS-Backend                                                                                                                          spring.application.name=AuthApp

spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=root123
server.port=1003
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sangavarganaraj@gmail.com
spring.mail.password=umye nosd xjmu sxom

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true